# Generated by Django 2.2.8 on 2020-01-10 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_brand_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='planqueue',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
