# Generated by Django 2.2.8 on 2020-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200116_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
