# Generated by Django 2.2.8 on 2020-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200118_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandplan',
            name='plan_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='planqueue',
            name='order_id',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
