# Generated by Django 2.2.8 on 2020-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200211_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
