# Generated by Django 2.2.8 on 2020-02-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200217_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuanityUnit',
            new_name='QuantityUnit',
        ),
    ]
