# Generated by Django 2.2.8 on 2020-02-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200217_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuantityUnit',
            new_name='MeasurementUnit',
        ),
        migrations.RenameField(
            model_name='measurementunit',
            old_name='name',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity_unit',
            new_name='measurement_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_food',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
    ]
