# Generated by Django 2.2.8 on 2020-02-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200217_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementunit',
            name='name',
            field=models.CharField(default='kg', max_length=20),
            preserve_default=False,
        ),
    ]
