# Generated by Django 2.2.8 on 2020-02-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_measurementunit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementunit',
            name='unit',
        ),
    ]
