# Generated by Django 3.0.3 on 2020-03-11 05:00

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200307_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='planqueue',
            name='product_space',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='brandapplication',
            name='errors',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
