# Generated by Django 2.2.8 on 2020-01-07 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planqueue',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ShopPlan'),
        ),
        migrations.AddField(
            model_name='planqueue',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Combo'),
        ),
        migrations.AddField(
            model_name='comboproduct',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='shop.ShopProduct'),
        ),
        migrations.AddField(
            model_name='combo',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='shop.Shop'),
        ),
    ]
