# Generated by Django 2.2.8 on 2020-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200112_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopplan',
            name='plan_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
