# Generated by Django 2.2.8 on 2020-02-03 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200120_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cluster',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
