# Generated by Django 2.2.8 on 2020-02-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200203_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularPlaces',
            new_name='PopularPlace',
        ),
    ]
