# Generated by Django 2.2.8 on 2020-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200203_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='about',
            field=models.CharField(default='About my shop', max_length=1024),
        ),
    ]
