# Generated by Django 2.2.8 on 2020-02-09 10:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_popularplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularplace',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='popular_places/'),
        ),
    ]
