# Generated by Django 2.2.8 on 2020-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200209_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='max_offered_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='combo',
            name='offered_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
