# Generated by Django 3.0.3 on 2020-03-06 09:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200212_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopapplication',
            name='status_description',
            field=models.CharField(default='Your application is under review. This usually takes 1 - 2 days.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='hero_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='shop_images/', verbose_name='shop hero image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='shop',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shopapplication',
            name='status',
            field=models.CharField(default='Under Review', max_length=30),
        ),
    ]
