# Generated by Django 3.0.3 on 2020-03-06 12:21

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200306_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='shopapplication',
            name='errors',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
