# Generated by Django 3.0.3 on 2020-03-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_measurementunit_unit'),
        ('shop', '0013_auto_20200306_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopapplication',
            name='status_description',
        ),
        migrations.AlterField(
            model_name='shopapplication',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ApplicationStatus'),
        ),
    ]
