# Generated by Django 3.0.3 on 2020-03-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200307_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopapplication',
            name='status',
        ),
    ]
