# Generated by Django 3.0.3 on 2020-03-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200307_1636'),
        ('shop', '0015_remove_shopapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopapplication',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ApplicationStatus'),
        ),
    ]
