# Generated by Django 3.0.3 on 2020-03-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_shopapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='planqueue',
            name='product_space',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
